[package]
name = "alloc"
version = "0.0.1"
authors = []


[dependencies.core]
path = "../core"

[features]
default  = []
external_funcs = []
external_crate = [ "external" ]

[dependencies.external]
git = "https://github.com/ryanra/RustOS.git"
optional = true
